name: password_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  crypt: ^4.2.1
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_screen_lock: ^9.0.1
  local_auth: ^2.1.6
  provider: ^6.0.5
  sqflite: ^2.2.7
  path: ^1.8.3
  url_launcher: ^6.1.10
  flex_color_scheme: ^7.0.4
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
